name: Build and Publish Docker Image on New Release

on:
  schedule:
    - cron: '0 5 * * *'
  # Allows manual trigger
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check branch
        id: check-branch
        run: |
          if [[ "$(git rev-parse --abbrev-ref HEAD)" == "main" ]]; then
            echo "::set-output name=on_main::true"
          else
            echo "::set-output name=on_main::false"
          fi

      - name: Get latest Hetzner Cloud CLI release
        if: steps.check-branch.outputs.on_main == 'true'
        id: latest-release
        run: |
          LATEST_VERSION=$(curl -s https://api.github.com/repos/hetznercloud/cli/releases/latest | jq -r .tag_name)
          echo "::set-output name=version::$LATEST_VERSION"

      - name: Build Docker image
        if: steps.check-branch.outputs.on_main == 'true'
        run: |
          docker build . --file Dockerfile --build-arg VERSION=${{ steps.latest-release.outputs.version }} -t micheljung/hcloud:${{ steps.latest-release.outputs.version }}

      - name: Log in to Docker Hub
        if: steps.check-branch.outputs.on_main == 'true'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image to Docker Hub
        if: steps.check-branch.outputs.on_main == 'true'
        run: |
          docker push micheljung/hcloud:${{ steps.latest-release.outputs.version }}
